name: Latex To PDF generator
# Build LaTex manuscripts and push the latest PDF back to GitHub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MANUSCRIPT_PATH: book/book # exclude the '.tex' / '.pdf' extension!
      LATEX: pdflatex -shell-escape
      BIBTEX: bibtex
    steps: 
    - uses: actions/checkout@v1
    - name: Install texlive
      run: |
        sudo apt-get install texlive-publishers \
                             texlive-latex-recommended \
                             texlive-latex-extra \
                             texlive-fonts-recommended \
                             texlive-fonts-extra
    - name: Build pdf
      run: |
        cd ${MANUSCRIPT_PATH%/*}
        ${LATEX} ${MANUSCRIPT_PATH##*/}.tex
        
    - name: Setup git config
      run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
  
    - name: Create a temporary artifact downloads folder
        run: mkdir downloads
        
    - name: step 2 - Add artifacts to publish to the temp folder
        run: |
          cp ${MANUSCRIPT_PATH##*/}.pdf downloads/.
          
   # - name: Step 3 - Use the Upload Artifact GitHub Action
    #    uses: actions/upload-artifact@v2
     #   with: 
        #  name: assets-for-download
         # path: downloads
      
   # - name: Push pdf
   #   run: |
   #     cd ${MANUSCRIPT_PATH%/*}
  #    git add -f ${MANUSCRIPT_PATH##*/}.pdf 
     #   git commit -m "Update book"
      #  git push 
